### ISSUE TITLE
Externalize the Flickr API Key Values

### ISSUE THREAD

**Issue by cgoodale** [IEPUG/image_project#8]
Right now we have simple placeholder variables for the FlickrAPI keys.  These values should be stored external to the code in either environment variables or in a config.ini file.

The code I saw that had the placeholders was located here:

flaskAPI/flickrAPI/pullImages.py

Either way, we will need to update the code and the associated README to spell out where these values need to be set.

**Comment by NerdsvilleCEO** [comment]
Sounds good, I will do that right now.

**Comment by NerdsvilleCEO** [comment]
Done. Updating documentation right now
